name: build and test

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '7.0.203'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build domain
      run: dotnet build ./Helper.Core.Tests --configuration Release --no-restore

    - name: Test domain
      run: dotnet test ./Helper.Core.Tests --no-restore --verbosity normal
      
    - name: Build core
      run: dotnet build ./Common/Common.Core.Tests --configuration Release --no-restore
    
    - name: Test core
      run: dotnet test ./Common/Common.Core.Tests --no-restore --verbosity normal